import { Roboto } from 'next/font/google'
import './global.css'

const robotoNormal = Roboto({
  weight: '400',
  subsets: ['latin']
})

const robotoBold = Roboto({
  weight: '700',
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
>
      <body className={robotoNormal.className}>{children}</body>
    </html>
  )
}
